console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 4
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#c39ff1'
    template = '  {{ .UserName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#89b4fa'
    template = ' 󰉋  {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'
      folder_separator_icon = '  '
      home_icon = '~'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#b4befe'
    template = '  {{ .HEAD }} '

    [blocks.segments.properties]
      fetch_status = false

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#a6e3a1'
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#f9e2af'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    type = 'exit'
    style = 'plain'
    foreground = '#1e1e2e'
    background = '#a6e3a1'
    background_templates = ['{{ if gt .Code 0 }}#f38ba8{{ end }}']
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#89dceb'
    background = 'transparent'
    template = '{{ .CurrentDate | date "15:04" }}'