# GlazeWM configuration file.
# I have used win as the modifier key for all keybindings for convenience reasons.
# You can change it to alt if you want to avoid overriding some default Windows shortcuts.

general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a shortcut to start Yasb.
  #startup_commands: ["shell-exec C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Yasb.lnk"]

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: false

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "window_focus"

     # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Gap between adjacent windows.
  inner_gap: "12px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "12px"
    right: "12px"
    bottom: "12px"
    left: "12px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#cba6f7"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#6c7086"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    display_name: "1"
    keep_alive: true
  - name: "2"
    display_name: "2"
    keep_alive: true
  - name: "3"
    display_name: "3"
    keep_alive: true
  - name: "4"
    display_name: "4"
  - name: "5"
    display_name: "5"
  - name: "6"
    display_name: "6"
  - name: "7"
    display_name: "7"
  - name: "8"
    display_name: "8"
  - name: "9"
    display_name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys.PowerAccent" }
        window_class: { regex: "HwndWrapper*" }

      # Ignore PotPlayer's mini player window.
      - window_process: { equals: 'PotPlayerMini64' }
        window_class: { equals: 'PotShadowWnd' }

      # Ignore dropshelf
      - window_process: { equals: 'Dropshelf' }
        window_class: { equals: 'WinUIDesktopWin32WindowClass' }

      #Ignore Phone Link Casted Windows
      - window_process: { equals: 'YourPhoneAppProxy' }
        window_class: { regex: 'HwndWrapper.*YourPhoneAppProxy.*' }
      
  - commands: ["toggle-floating --centered"]
    match:
      #- window_process: { equals: "SomeApp.exe" }
      #  window_class: { regex: "SomeAppClass" }

binding_modes:
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["win+shift+p"]

keybindings:
  # Disables all keybindings until win+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["win+shift+p"]

  # Resize focused window.
  - commands: ["resize --width -2%"]
    bindings: ["win+,"]
  - commands: ["resize --width +2%"]
    bindings: ["win+."]
  - commands: ["resize --height +2%"]
    bindings: ["win+up"]
  - commands: ["resize --height -2%"]
    bindings: ["win+down"]

  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["win+h"]
  - commands: ["focus --direction right"]
    bindings: ["win+l"]
  - commands: ["focus --direction up"]
    bindings: ["win+k"]
  - commands: ["focus --direction down"]
    bindings: ["win+j"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["win+shift+h", "win+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["win+shift+l", "win+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["win+shift+k", "win+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["win+shift+j", "win+shift+down"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["win+shift+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["win+shift+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["win+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["win+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["win+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["win+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["win+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["win+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["win+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["win+shift+d"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["win+shift+c"]
  - commands: ["focus --prev-workspace"]
    bindings: ["win+shift+z"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["win+w"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["win+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["win+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["win+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["win+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["win+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["win+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["win+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["win+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["win+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["win+shift+j"]
  - commands: ["move-workspace --direction right"]
    bindings: ["win+shift+l"]
  - commands: ["move-workspace --direction up"]
    bindings: ["win+shift+i"]
  - commands: ["move-workspace --direction down"]
    bindings: ["win+shift+k"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["win+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["win+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["win+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["win+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["win+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["win+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["win+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["win+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["win+shift+9"]

  ## Custom keybindings for applications.
  ## Adjust these to your needs. You can also add more keybindings for other applications here.

  # Launch terminal with the default profile.
  - commands: ["shell-exec C:\\Program Files\\PowerShell\\7\\pwsh.exe"]
    bindings: ["win+enter"]

  # Launch terminal as administrator
  - commands: ["shell-exec C:\\Scripts\\wtadmin.vbs"]
    bindings: ["win+shift+enter"]

  - commands: ["shell-exec zen"]
    bindings: ["win+b"]

  - commands: ["shell-exec code"]
    bindings: ["win+c"]

  - commands: ["shell-exec %USERPROFILE%\\Desktop\\Discord.lnk"]
    bindings: ["win+d"]

  - commands: ["shell-exec %AppData%\\Spotify\\Spotify.exe"]
    bindings: ["win+s"]

  # An open source YouTube Music client: https://github.com/th-ch/youtube-music
  - commands: ["shell-exec %USERPROFILE%\\scoop\\apps\\pear-desktop\\current\\YouTube Music.exe"]
    bindings: ["win+y"]

  ## Be careful while using win+ combinations as it may override important default Windows shortcuts. So you won't be able to access those native features with shortcuts unless you pause keybindings using win+shift+p, or close GlazeWM.
  # Some important default Windows shortcuts that you should avoid overriding:
  # win+e: Open File Explorer
  # win+n: Open Notification Center
  # win+a: Open Action Center
  # win+d: Show Desktop (I overrode this since I use 3 finger swipe down touchpad gesture to show desktop, but you may want to change it back)
  # win+s: Open Search (I overrode this since you can directly start searching after opening start menu, but you may want to change it back)
  # win+shift+s: Snip Screen
  # win+shift+t: OCR Screen (Windows 11)
  # win+. and win+;: Open Emoji Panel (I overrode win+. for resizing, but win+; still works for opening emoji panel)
  # win+v: Open Clipboard History
